# Generated by Django 4.2.11 on 2024-05-03 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr_zipcode', models.CharField(max_length=255)),
                ('addr_street', models.CharField(max_length=255)),
                ('addr_number', models.CharField(max_length=255)),
                ('addr_complement', models.CharField(max_length=255)),
                ('addr_distritc', models.CharField(max_length=255)),
                ('addr_city', models.CharField(max_length=255)),
                ('addr_state', models.CharField(max_length=255)),
                ('addr_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='userAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_lastname', models.CharField(max_length=255)),
                ('user_document', models.CharField(max_length=255)),
                ('user_phone', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=255)),
                ('user_registration', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_customer.adress')),
            ],
        ),
    ]
