# Generated by Django 4.2.11 on 2024-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='addr_complement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='adress',
            name='addr_country',
            field=models.CharField(default='Brasil', max_length=255),
        ),
    ]
