# Generated by Django 4.2.11 on 2024-05-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0004_companyadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='addr_distritc',
            new_name='addr_district',
        ),
    ]
