# Generated by Django 4.2.11 on 2024-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0005_rename_addr_distritc_adress_addr_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadd',
            name='company_document',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='useradd',
            name='user_document',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
